root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/worker"
cmd = "go build -o ./tmp/worker ./cmd/worker"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata", "examples", "scripts", "logs"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = "bash -c 'set -a; source .env.worker.dev; set +a; exec ./tmp/worker 2>&1 | tee logs/worker.log'"
include_dir = ["cmd/worker", "service", "cmd/forohtoo"]
include_ext = ["go"]
include_file = []
kill_delay = "0s"
log = "logs/air-worker.log"
poll = false
poll_interval = 0
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
