apiVersion: apps/v1
kind: Deployment
metadata:
  name: forohtoo-worker
  labels:
    app: forohtoo-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forohtoo-worker
  template:
    metadata:
      labels:
        app: forohtoo-worker
    spec:
      containers:
      - name: worker
        image: brojonat/forohtoo:379ac2d925ff03e491b884f4d236641394cf6673
        imagePullPolicy: Always
        command: ["/worker"]
        envFrom:
        - secretRef:
            name: forohtoo-secret-worker-envs
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      imagePullSecrets:
      - name: regcred
