// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	Signature string `json:"signature"`
	// Destination wallet address (receiver/monitored wallet)
	WalletAddress      string             `json:"wallet_address"`
	Slot               int64              `json:"slot"`
	BlockTime          pgtype.Timestamptz `json:"block_time"`
	Amount             int64              `json:"amount"`
	TokenMint          pgtype.Text        `json:"token_mint"`
	Memo               pgtype.Text        `json:"memo"`
	ConfirmationStatus string             `json:"confirmation_status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	// Source wallet address (sender) - NULL if cannot be determined
	FromAddress pgtype.Text `json:"from_address"`
	// Solana network where transaction occurred (mainnet, devnet, testnet)
	Network string `json:"network"`
}

type Wallet struct {
	Address                string             `json:"address"`
	PollInterval           pgtype.Interval    `json:"poll_interval"`
	LastPollTime           pgtype.Timestamptz `json:"last_poll_time"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	Network                string             `json:"network"`
	AssetType              string             `json:"asset_type"`
	TokenMint              string             `json:"token_mint"`
	AssociatedTokenAddress pgtype.Text        `json:"associated_token_address"`
}
