// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: wallets.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (
    address,
    network,
    poll_interval,
    status
) VALUES (
    $1, $2, $3, $4
)
RETURNING address, poll_interval, last_poll_time, status, created_at, updated_at, network
`

type CreateWalletParams struct {
	Address      string          `json:"address"`
	Network      string          `json:"network"`
	PollInterval pgtype.Interval `json:"poll_interval"`
	Status       string          `json:"status"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.Address,
		arg.Network,
		arg.PollInterval,
		arg.Status,
	)
	var i Wallet
	err := row.Scan(
		&i.Address,
		&i.PollInterval,
		&i.LastPollTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
	)
	return i, err
}

const deleteWallet = `-- name: DeleteWallet :exec
DELETE FROM wallets
WHERE address = $1 AND network = $2
`

type DeleteWalletParams struct {
	Address string `json:"address"`
	Network string `json:"network"`
}

func (q *Queries) DeleteWallet(ctx context.Context, arg DeleteWalletParams) error {
	_, err := q.db.Exec(ctx, deleteWallet, arg.Address, arg.Network)
	return err
}

const getWallet = `-- name: GetWallet :one
SELECT address, poll_interval, last_poll_time, status, created_at, updated_at, network FROM wallets
WHERE address = $1 AND network = $2
`

type GetWalletParams struct {
	Address string `json:"address"`
	Network string `json:"network"`
}

func (q *Queries) GetWallet(ctx context.Context, arg GetWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, arg.Address, arg.Network)
	var i Wallet
	err := row.Scan(
		&i.Address,
		&i.PollInterval,
		&i.LastPollTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
	)
	return i, err
}

const listActiveWallets = `-- name: ListActiveWallets :many
SELECT address, poll_interval, last_poll_time, status, created_at, updated_at, network FROM wallets
WHERE status = 'active'
ORDER BY last_poll_time ASC NULLS FIRST
`

func (q *Queries) ListActiveWallets(ctx context.Context) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, listActiveWallets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wallet
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.Address,
			&i.PollInterval,
			&i.LastPollTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Network,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWallets = `-- name: ListWallets :many
SELECT address, poll_interval, last_poll_time, status, created_at, updated_at, network FROM wallets
ORDER BY created_at DESC
`

func (q *Queries) ListWallets(ctx context.Context) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, listWallets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wallet
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.Address,
			&i.PollInterval,
			&i.LastPollTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Network,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWalletPollTime = `-- name: UpdateWalletPollTime :one
UPDATE wallets
SET
    last_poll_time = $3,
    updated_at = NOW()
WHERE address = $1 AND network = $2
RETURNING address, poll_interval, last_poll_time, status, created_at, updated_at, network
`

type UpdateWalletPollTimeParams struct {
	Address      string             `json:"address"`
	Network      string             `json:"network"`
	LastPollTime pgtype.Timestamptz `json:"last_poll_time"`
}

func (q *Queries) UpdateWalletPollTime(ctx context.Context, arg UpdateWalletPollTimeParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWalletPollTime, arg.Address, arg.Network, arg.LastPollTime)
	var i Wallet
	err := row.Scan(
		&i.Address,
		&i.PollInterval,
		&i.LastPollTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
	)
	return i, err
}

const updateWalletStatus = `-- name: UpdateWalletStatus :one
UPDATE wallets
SET
    status = $3,
    updated_at = NOW()
WHERE address = $1 AND network = $2
RETURNING address, poll_interval, last_poll_time, status, created_at, updated_at, network
`

type UpdateWalletStatusParams struct {
	Address string `json:"address"`
	Network string `json:"network"`
	Status  string `json:"status"`
}

func (q *Queries) UpdateWalletStatus(ctx context.Context, arg UpdateWalletStatusParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWalletStatus, arg.Address, arg.Network, arg.Status)
	var i Wallet
	err := row.Scan(
		&i.Address,
		&i.PollInterval,
		&i.LastPollTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
	)
	return i, err
}

const walletExists = `-- name: WalletExists :one
SELECT EXISTS(SELECT 1 FROM wallets WHERE address = $1 AND network = $2)
`

type WalletExistsParams struct {
	Address string `json:"address"`
	Network string `json:"network"`
}

func (q *Queries) WalletExists(ctx context.Context, arg WalletExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, walletExists, arg.Address, arg.Network)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
